'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const requests=[];
const dummy={innerHTML:'',open:false,addEventListener(){},classList:{remove(){}},setAttribute(){}};
const context=vm.createContext({document:{querySelector:()=>dummy,querySelectorAll:()=>[],addEventListener(){},body:dummy},location:{hash:'#monitor'},window:{addEventListener(){},scrollTo(){},lucide:{createIcons(){}}},console,crypto:globalThis.crypto,setTimeout:()=>1,clearTimeout(){},fetch:url=>{
 if(url.startsWith('/api/state'))return Promise.resolve({ok:true,json:async()=>({collector:{tasks:[]}})});
 return new Promise(resolve=>requests.push({url,resolve}));
}});
const run=s=>vm.runInContext(s,context);
vm.runInContext(fs.readFileSync('static/app.js','utf8'),context);
const actualRedraw=run('redrawMonitorResults');
run("render=()=>{};syncFreshnessHint=()=>{};redrawMonitorResults=()=>{};redrawWorkPool=()=>{};");
const reply=(request,value)=>request.resolve({ok:true,json:async()=>value});
const result=(video,page=1)=>({rows:[{text:video,video_url:video}],counts:{observed:28,accepted:20,filtered:8},valuable_count:2,page,pages:2,total:28,scope:'all_local_comment_history'});
const deadline=setTimeout(()=>{console.error('FAIL: history fixture left an unresolved request');process.exitCode=1;},10000);
(async()=>{
 await new Promise(r=>setImmediate(r));
 assert.match(requests[0].url,/\/api\/monitor-comments/,'Initial history starts before the shell finishes');
 reply(requests.shift(),result('initial'));await new Promise(r=>setImmediate(r));
 const first=run("changeMonitorSelection('video-A')"),second=run("changeMonitorSelection('video-B')");
 reply(requests[1],result('video-B'));await second;
 reply(requests[0],result('video-A'));await first;
 assert.equal(run('monitorResults().rows[0].text'),'video-B','Late work A cannot replace selected work B');
 run('redrawMonitorResults=()=>monitorResultsPanel();');
 const next=run("handleAction({dataset:{action:'monitor-result-page',step:'1'}})");
 assert.match(requests[2].url,/page=2/,'Loading state must not clamp a requested next page back to 1');
 reply(requests[2],result('video-B',2));await next;
 assert.equal(run('monitorResultPage'),2);
 const all=run("handleAction({dataset:{action:'work-clear'}})");
 assert.match(requests[3].url,/video=&/);reply(requests[3],result('all'));await all;
 assert.equal(run('monitorResultVideo'),'');assert.equal(run('monitorResultPage'),1);
 const stale=run("changeMonitorSelection('video-C')");run("mode='demo'");
 reply(requests[4],result('video-C'));await stale;
 assert.equal(run('monitorHistory.rows[0].text'),'all','Late response must not cross workspace');
 run("mode='live';monitorResultVideo='';monitorResultFilter='valuable';monitorResultPage=1");
 const switchTo=filter=>run(`handleActionClick({target:{closest:()=>({dataset:{action:'monitor-result-filter',filter:'${filter}'},tagName:'BUTTON',disabled:false,isConnected:true})},preventDefault(){}})`);
 let pending=switchTo('accepted');
 let html=run('monitorResultsPanel()');
 assert.match(html,/采集通过 <b>20<\/b>/,'Known counts survive a first visit to a filter');
 assert.match(html,/点单（板板） <b>2<\/b>/);
 assert.match(html,/aria-busy="true"/);assert.match(html,/role="status"/);
 assert.doesNotMatch(html,/暂无|0 条符合查看条件/,'Loading cannot masquerade as no results');
 assert.match(html,/data-step="1" disabled/);
 reply(requests.at(-1),{...result('accepted-row'),counts:{observed:30,accepted:22,filtered:8}});await pending;
 pending=switchTo('valuable');
 assert.equal(run('monitorResults().rows[0].text'),'all','Revisiting a filter uses its own cached rows');
 assert.equal(run('monitorResults().counts.observed'),30,'Cached tabs use the newest counts for this work scope');
 assert.match(run('monitorResultsPanel()'),/已显示上次结果/);
 reply(requests.at(-1),result('valuable-row'));await pending;
 pending=switchTo('filtered');const failedRequest=requests.at(-1);
 failedRequest.resolve({ok:false,json:async()=>({error:'fixture failure'})});await pending;
 html=run('monitorResultsPanel()');assert.match(html,/评论未能加载，请重试/);assert.doesNotMatch(html,/暂无/);
 pending=run("handleAction({dataset:{action:'monitor-history-retry'}})");
 assert.match(run('monitorResultsPanel()'),/aria-busy="true"/,'Retry immediately replaces the stale error');
 reply(requests.at(-1),{...result('filtered-row'),rows:[],total:0,pages:1});await pending;
 assert.match(run('monitorResultsPanel()'),/暂无可展示的评论/,'Confirmed empty results may show an empty state');
 const old=switchTo('all'),oldRequest=requests.at(-1),current=switchTo('accepted');
 assert.equal(run('monitorResultFilter'),'accepted','A second tab click must be handled before the first response returns');
 assert.equal(run('busy'),false,'Browsing must not lock unrelated navigation for the network round trip');
 reply(requests.at(-1),result('current-accepted'));await current;
 oldRequest.resolve({ok:false,json:async()=>({})});await old;
 assert.equal(run('monitorResults().rows[0].text'),'current-accepted');
 assert.doesNotMatch(run('monitorResultsPanel()'),/role="alert"/,'A late error cannot contaminate the active filter');
 pending=run("changeMonitorSelection('uncached-work')");
 html=run('monitorResultsPanel()');assert.match(html,/全部观察 <b>—<\/b>/,'Unknown work counts are not inherited or invented as zero');
 reply(requests.at(-1),result('uncached-work'));await pending;
 run("monitorHistory=null;monitorHistoryKey='';monitorHistoryCache.clear();monitorHistoryCounts.clear()");
 html=run('monitorResultsPanel()');assert.match(html,/aria-busy="true"/);assert.doesNotMatch(html,/暂无/);
 run(`S={collector:{board:{rows:['reading','queued','monitoring','attention','paused','history'].map((state,i)=>({id:i+1,state,continuous_monitoring:state==='monitoring',title:state,external_id:String(i),url:String(i)}))}}};workFilter='all';`);
 html=run('workPool()');assert.match(html,/全部作品 6/);assert.match(html,/跟踪中 3/);
 for(const state of ['监控待处理','监控已暂停','未纳入持续监控'])assert.ok(html.includes(state));
 run("workFilter='tracked'");html=run('workPool()');
 assert.doesNotMatch(html,/work-item-title[^>]*>attention|work-item-title[^>]*>paused|work-item-title[^>]*>history/);
 const explained={text:'找陪练 <img src=x>',analysis_method:'model',analysis_state:'model',analysis_reason:'有明确需求 <script>alert(1)</script>',analysis_evidence:[{kind:'category',source:'comment',text:'找陪练 <img src=x>'},{kind:'game',source:'video',text:'仅标题依据'},{kind:'category',source:'comment',text:'不在原文'}]};
 context.explained=explained;
 html=run('analysisReason(explained)');
 assert.match(html,/模型理由/);assert.match(html,/原文依据/);assert.match(html,/&lt;script&gt;/);assert.match(html,/&lt;img src=x&gt;/);
 assert.doesNotMatch(html,/<script>|<img|仅标题依据|不在原文/);
 html=run("analysisReason({...explained,analysis_method:'rules',analysis_state:'failed',analysis_reason:'合成规则依据'})");
 assert.match(html,/规则依据/);assert.doesNotMatch(html,/模型理由|原文依据/,'Failed model must not lend its explanation to a rules result');
 assert.match(run("analysisReason({...explained,analysis_method:'human'})"),/人工理由/);
 assert.match(run("analysisReason({...explained,analysis_reason:null})"),/历史结果未保存判断理由/);
 for(const state of ['snapshot_changed','missing','pending'])assert.equal(run(`analysisReason({...explained,analysis_state:'${state}'})`),'');
 assert.equal(run("analysisReason({...explained,filter_reason:'filtered_blocked'})"),'');
 context.stageRow={...explained,companion_relevance:{passed:false,reason:'排除依据 <script>alert(1)</script>',evidence:[{source:'comment',text:explained.text},{source:'comment',text:'不在原文'},{source:'unknown',text:'错误来源'}]}};
 html=run('commentStages(stageRow)');
 assert.match(html,/采集通过/);assert.match(html,/当前陪玩初筛/);assert.match(html,/保留历史模型结果/);
 assert.match(html,/&lt;script&gt;/);assert.match(html,/&lt;img src=x&gt;/);assert.doesNotMatch(html,/<script>|<img|不在原文|错误来源/);
 assert.match(run('analysisCaption(stageRow)'),/模型分析完成/,'A new relevance policy cannot rewrite a historical model result');
 assert.doesNotMatch(run("commentStages({...stageRow,filter_reason:'filtered_old'})"),/当前陪玩初筛|查看依据/,'Collection rejection must not masquerade as a relevance outcome');
 assert.match(run("commentStages({...stageRow,analysis_state:'snapshot_changed'})"),/暂无结果/,'Mismatched comment snapshots cannot display a gate for other text');
 assert.match(run("analysisCaption({...stageRow,analysis_method:'rules',analysis_state:'skipped'})"),/陪玩初筛未通过/);
 run("monitorResultVideo='';monitorResultFilter='accepted';monitorResultQuery='';monitorHistory={...monitorHistory,rows:[explained]};monitorHistoryKey=historyKey();");
 assert.match(run('monitorResultsPanel()'),/data-action="comment-details"/);
 assert.doesNotMatch(run('monitorResultsPanel()'),/模型理由/,'Supporting evidence stays out of the primary row');
 run("showModal=(title,content)=>{globalThis.detailContent=content};monitorHistory.rows=[{...explained,video_url:'video-A',external_id:'comment-A'}];");
 await run("handleAction({dataset:{action:'comment-details',url:'video-A',key:'comment-A'}})");
 assert.match(context.detailContent,/模型理由/,'Details still expose the saved model explanation');
 assert.match(context.detailContent,/&lt;script&gt;/);
 assert.doesNotMatch(context.detailContent,/<script>|<img/);
 context.stageRow={...context.stageRow,video_url:'video-A',external_id:'comment-A'};
 const detailId=run('commentStages(stageRow)').match(/<details id="([^"]+)"/)[1];
 const otherId=run("commentStages({...stageRow,video_url:'video-B'})").match(/<details id="([^"]+)"/)[1];
 assert.notEqual(detailId,otherId,'Expansion belongs to the same work and comment');
 let restored=false,focused=false;
 const scroll={scrollTop:112,scrollLeft:0};
 const refreshedDetail={tagName:'DETAILS',set open(value){restored=value;},querySelector:()=>({focus(){focused=true;}})};
 const panel={set outerHTML(value){assert.match(value,/data-action="comment-details"/);scroll.scrollTop=0;}};
 context.document.querySelector=selector=>selector==='#monitor-result-panel'?panel:scroll;
 context.document.querySelectorAll=()=>[{id:detailId}];
 context.document.getElementById=id=>id===detailId?refreshedDetail:null;
 context.document.activeElement={tagName:'SUMMARY',closest:()=>({id:detailId})};
 run('monitorHistory.rows=[stageRow];');
 actualRedraw();
 assert.equal(restored,true,'Refreshing results keeps the same comment explanation open');
 assert.equal(focused,true,'Keyboard focus remains on its explanation toggle');
 assert.equal(scroll.scrollTop,112,'Refreshing an explanation preserves result scroll position');
 run("S.collector={tasks:[{id:99,status:'network_error',detail:'HTTP 连接失败，未自动重试。',active:false}],monitor:{enabled:true,status:'running',last_task_id:99,next_run_at:'2026-09-15T03:41:47Z'}};");
 assert.match(run('monitorOverview()'),/已安排 .* 自动重试/,'A scheduled retry shows the current monitor state');
 assert.doesNotMatch(run('monitorOverview()'),/未自动重试/);
 run("S.collector.monitor.enabled=false;S.collector.monitor.status='attention';");
 assert.doesNotMatch(run('monitorOverview()'),/已安排 .* 自动重试/,'A paused monitor must not promise a retry');
 run("S.collector.tasks[0].status='completed';");
 assert.doesNotMatch(run('monitorOverview()'),/最近批次 #99/,'Successful recovery removes the old warning');
 console.log('PASS: request races, pagination, stable loading counts, scoped caches, error/retry, workspace isolation, honest empty states, explanation escaping and expansion/focus preservation. Local fixtures only.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>clearTimeout(deadline));
