'use strict';
// Deterministic UI state and request tests. Not a browser or phone acceptance test.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map(),events=new Map(),timers=new Map(),requests=[];
let timer=0;
const node=id=>{if(!elements.has(id))elements.set(id,{value:'',textContent:'',innerHTML:'',dataset:{},hidden:false,disabled:false,checked:false,className:'',classList:{toggle(){},remove(){}},setAttribute(){},focus(){},closest:()=>null});return elements.get(id);};
let next={available:true,active:false,config:{account:'1267597446',auto_recover:false},relay:{ready:false,paired:false,origin:''},checks:{},session:{ready:true},history:[],csrf:'fixture-csrf',resume_candidates:[]};
const document={hidden:false,querySelector:node,addEventListener:(key,fn)=>events.set(key,fn),body:node('body')};
const context=vm.createContext({document,window:{lucide:{createIcons(){}},addEventListener(){}},console,setTimeout:(fn,ms)=>{timers.set(++timer,{fn,ms});return timer;},clearTimeout:id=>timers.delete(id),fetch:async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>options?{result:url.endsWith('phone')?{origin:'https://fixture.example.test',authorization:'Bearer fixture-phone-secret',account:'1267597446'}:{}}:next};}});
const run=code=>vm.runInContext(code,context);
vm.runInContext(fs.readFileSync('static/login.js','utf8'),context);
(async()=>{
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(requests.length,1);assert.equal(requests[0].url,'/api/login-recovery');
  assert.ok(requests.every(r=>!r.options),'Opening the page performs no writes');
  assert.equal(node('#start-login').disabled,true);assert.equal(node('#auto-recover').disabled,true);
  assert.equal(node('#setup-link').hidden,false,'Unpaired state offers the setup action');
  assert.equal(node('#resume-choice').hidden,true,'Cannot select a resume action before pairing');
  node('#login-account').value='unsaved-account';node('#login-account').closest=()=>node('#recovery-form');
  events.get('input')({target:node('#login-account')});
  next={...next,config:{...next.config,account:'server-account'}};await run('refresh()');
  assert.equal(node('#login-account').value,'unsaved-account','Polling preserves edits after blur');
  assert.equal(node('#start-login').disabled,true,'Save account changes before login');
  run('dirty=false');await run('refresh()');assert.equal(node('#login-account').value,'server-account');
  next={...next,relay:{ready:true,paired:true,origin:'https://fixture.example.test'},checks:{health_at:1,phone_test_at:2}};await run('refresh()');
  assert.equal(node('#auto-recover').disabled,false);assert.equal(node('#start-login').disabled,false);
  next={...next,active:true,job:{id:'a'.repeat(32),kind:'login',status:'waiting_sms',account:'fixture',created_at:1}};await run('refresh()');
  assert.equal(node('#manual-complete').hidden,false);assert.equal(node('#cancel-login').hidden,false);
  assert.equal(node('#save-config').disabled,true);assert.equal(node('#start-login').disabled,true);
  assert.equal([...timers.values()].at(-1).ms,2000);
  await run("post('login-recovery-complete',{id:state.job.id})");
  const write=requests.at(-1);assert.equal(write.url,'/api/login-recovery-complete');assert.equal(write.options.headers['X-ClubOps-Token'],'fixture-csrf');
  assert.equal(JSON.parse(write.options.body).id,'a'.repeat(32));
  next={...next,active:false};await run('refresh()');
  events.get('click')({target:{closest:selector=>selector==='[data-command]'?{dataset:{command:'show-phone'}}:null}});
  await new Promise(resolve=>setImmediate(resolve));
  const phoneConfig=JSON.parse(node('#phone-scriptable').value);
  assert.equal(phoneConfig.account,'1267597446');assert.equal(phoneConfig.authorization,'Bearer fixture-phone-secret');
  assert.equal(node('#phone-credentials').hidden,false);
  node('#phone-credentials').hidden=false;node('#phone-authorization').value='private-fixture';node('#phone-origin').value='https://fixture.example.test';
  node('#phone-scriptable').value='private-fixture-json';document.hidden=true;events.get('visibilitychange')();
  assert.equal(node('#phone-credentials').hidden,true);assert.equal(node('#phone-authorization').value,'');assert.equal(timers.size,0);
  assert.equal(node('#phone-scriptable').value,'');
  const html=fs.readFileSync('static/login.html','utf8');
  for(const match of fs.readFileSync('static/login.js','utf8').matchAll(/\$\('#([\w-]+)'\)/g))assert.ok(html.includes(`id="${match[1]}"`),`Missing element ${match[1]}`);
  assert.ok(html.includes('id="phone-credentials" hidden'));assert.ok(!html.includes('onclick='));
  run("state={available:true,active:false,history:[{status:'resume_pending'}]}");assert.match(run('topStatus(state)[0]'),/采集待继续/);
  run("state={available:true,active:false,history:[{status:'cancelled'}]}");assert.equal(run('topStatus(state)[0]'),'本次登录已取消');
  console.log('PASS: login UI read-only entry, draft preservation, guarded actions, active polling, secret hiding and real element IDs. Synthetic only.');
})().catch(error=>{console.error(error);process.exitCode=1;});
