'use strict';
// Deterministic read-only local polling tests. No browser, network or live database.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map(),timers=new Map(),events=new Map(),windowEvents=new Map(),requests=[];
let timerId=0,next={tasks:[],plans:[]},fail=false,deferred;
const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',outerHTML:'',open:false,addEventListener(){},classList:{remove(){}},setAttribute(){}});return elements.get(id);};
const document={hidden:false,activeElement:{matches:()=>false},querySelector:el,querySelectorAll:()=>[],addEventListener:(type,fn)=>events.set(type,fn),body:el('body')};
const context=vm.createContext({document,location:{hash:'#monitor'},window:{addEventListener:(type,fn)=>windowEvents.set(type,fn),scrollTo(){},lucide:{createIcons(){}}},setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;},clearTimeout:id=>timers.delete(id),console,crypto:globalThis.crypto,fetch:async url=>{
  requests.push(url);if(deferred)return deferred;
  if(fail)throw Error('synthetic offline');
  return {ok:true,json:async()=>url.startsWith('/api/state')?{collector:next}:{...next}};
}});
const run=code=>vm.runInContext(code,context);
vm.runInContext(fs.readFileSync('static/app.js','utf8'),context);
run("syncFreshnessHint=()=>{};refreshMonitorHistory=async()=>{};render=()=>{};collectorPanel=()=>JSON.stringify(S.collector);schedulePanel=()=>JSON.stringify(S.collector.plans);monitorOverview=()=>JSON.stringify(S.collector.monitor);workPool=()=>JSON.stringify(S.collector.board||{});monitorSettingsPanel=()=>JSON.stringify(S.collector.monitor);monitorResultsPanel=()=>JSON.stringify(S.collector.results);toast=()=>{};");
(async()=>{
  await new Promise(r=>setImmediate(r));
  assert.equal([...timers.values()].at(-1).ms,15000,'Idle tabs must discover externally-created tasks');
  run('let loads=0;load=async()=>{loads++;};');
  next={tasks:[{id:1,status:'running',active:true}],plans:[],monitor:{enabled:true},results:{rows:[{text:'synthetic observation'}]}};await run('pollCollection()');
  assert.match(el('#monitor-result-panel').outerHTML,/synthetic observation/,'Active observations update the central results table');
  assert.equal(el('#monitor-overview').outerHTML,'{"enabled":true}');
  assert.equal(el('#monitor-settings').outerHTML,'{"enabled":true}');
  assert.equal(run('S.collector.tasks[0].id'),1);assert.match(el('#collection-panel').outerHTML,/running/);
  assert.equal([...timers.values()].at(-1).ms,2500);assert.equal(run('loads'),0);
  el('#modal').open=true;next={tasks:[{id:1,status:'needs_login',active:true}],plans:[]};await run('pollCollection()');
  assert.ok(!el('#collection-panel').outerHTML.includes('needs_login'),'Do not disturb an open modal');
  el('#modal').open=false;await run('pollCollection()');assert.match(el('#collection-panel').outerHTML,/needs_login/);
  run('monitorDraftDirty=true');
  const draftBefore=el('#monitor-settings').outerHTML;
  next={tasks:[{id:1,status:'running',active:true}],plans:[],monitor:{enabled:false,include_keywords:'new server value'}};
  await run('pollCollection()');
  assert.equal(el('#monitor-settings').outerHTML,draftBefore,'Unsaved config survives blur and background refresh');
  run('monitorDraftDirty=false');await run('pollCollection()');
  assert.match(el('#monitor-settings').outerHTML,/new server value/);
  document.activeElement.matches=()=>true;next={tasks:[{id:1,status:'completed',active:false}],plans:[]};await run('pollCollection()');assert.equal(run('loads'),0);
  document.activeElement.matches=()=>false;await run('pollCollection()');assert.equal(run('loads'),1);
  await run('pollCollection()');assert.equal(run('loads'),1,'Unchanged terminal state must not re-render repeatedly');
  run("page='live';liveDraftDirty=true;liveStatus=()=>JSON.stringify(S.collector.live_monitor.current);liveResults=()=>JSON.stringify(S.collector.live_monitor.rows);");
  next={tasks:[],plans:[],live_monitor:{config:{room_url:'https://live.douyin.com/123456'},active_id:7,current:{status:'running'},rows:[{text:'live synthetic observation'}]}};
  await run('pollCollection()');assert.equal(run('loads'),1,'Live config editing prevents whole-page refresh');
  assert.match(el('#live-results').outerHTML,/live synthetic observation/);assert.match(el('#live-status').outerHTML,/running/);assert.equal([...timers.values()].at(-1).ms,2500);
  run('liveDraftDirty=false');next={...next,live_monitor:{...next.live_monitor,rows:[...next.live_monitor.rows,{text:'second'}]}};await run('pollCollection()');assert.equal(run('loads'),1,'Active live data only redraws results and status');assert.match(el('#live-results').outerHTML,/second/);
  run("liveScope='all';liveArchive={rows:[]};liveArchiveModelKey='null';let archiveUpdates=0;refreshLiveArchive=async(force,background)=>{if(force&&background){archiveUpdates++;liveArchiveModelKey=JSON.stringify(S.collector.model_queue||null);}};");
  next={...next,model_queue:{completed:13}};await run('pollCollection()');
  assert.equal(run('archiveUpdates'),1,'Model completion refreshes older archived sessions');
  await run('pollCollection()');assert.equal(run('archiveUpdates'),1,'Unchanged model state avoids redundant archive requests');
  run('liveDraftDirty=true');next={...next,model_queue:{completed:14}};await run('pollCollection()');
  assert.equal(run('archiveUpdates'),1,'Editing postpones archive refresh');
  run('liveDraftDirty=false');await run('pollCollection()');assert.equal(run('archiveUpdates'),2,'Refresh resumes after editing even when collector state is unchanged');
  run("liveScope='current'");
  run('liveDraftDirty=true');next={...next,live_monitor:{...next.live_monitor,active_id:null,current:{status:'cancelled'}}};await run('pollCollection()');assert.equal(run('loads'),1,'Draft survives a terminal event after blur');assert.match(el('#live-status').outerHTML,/cancelled/);
  run("location.hash='#monitor';stashDraft=()=>{};");windowEvents.get('hashchange')();assert.equal(run('liveDraftDirty'),false,'Leaving the page clears the discarded draft flag');
  next={tasks:[{id:1,status:'completed',active:false}],plans:[]};await run('pollCollection()');assert.equal(run('loads'),2);
  run("page='settings';semanticDraftDirty=true");
  next={tasks:[{id:1,status:'failed',active:false}],plans:[]};await run('pollCollection()');assert.equal(run('loads'),2,'Unsaved model settings survive a background task transition after blur');
  run('semanticDraftDirty=false');await run('pollCollection()');assert.equal(run('loads'),3);
  next={tasks:[{id:1,status:'completed',active:false}],plans:[]};await run('pollCollection()');
  fail=true;await run('pollCollection()');assert.equal(run('S.collector.tasks[0].status'),'completed');fail=false;
  document.hidden=true;events.get('visibilitychange')();assert.equal(timers.size,0);const before=requests.length;await run('pollCollection()');assert.equal(requests.length,before);document.hidden=false;
  let resolve;deferred=new Promise(r=>resolve=r);const pending=run('pollCollection()');await run('pollCollection()');assert.equal(requests.length,before+1,'Only one polling request in flight');
  run("mode='demo'");resolve({ok:true,json:async()=>({tasks:[{id:99,active:true}],plans:[]})});await pending;assert.equal(run('S.collector.tasks[0].id'),1,'Late response must not cross workspaces');assert.equal(timers.size,0);
  assert.ok(requests.every(url=>url.startsWith('/api/')),'Status polling never initiates platform collection');
  console.log('PASS: idle/active local polling, hidden tabs, deferred redraw, no duplicate fetch, failure recovery and workspace race. Synthetic only.');
})().catch(e=>{console.error(e);process.exitCode=1;});
