'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const requests=[],listeners={};
const dummy={innerHTML:'',open:false,addEventListener(){},classList:{remove(){}},setAttribute(){}};
const context=vm.createContext({document:{querySelector:()=>dummy,querySelectorAll:()=>[],addEventListener:(name,handler)=>listeners[name]=handler,body:dummy},location:{hash:'#live'},window:{addEventListener(){},scrollTo(){},lucide:{createIcons(){}}},URLSearchParams,console,crypto:globalThis.crypto,setTimeout:()=>1,clearTimeout(){},fetch:url=>{
 if(url.startsWith('/api/state'))return Promise.resolve({ok:true,json:async()=>({collector:{tasks:[]}})});
 return new Promise(resolve=>requests.push({url,resolve}));
}});
const run=s=>vm.runInContext(s,context);
vm.runInContext(fs.readFileSync('static/app.js','utf8'),context);
run('render=()=>{};redrawLiveResults=()=>{};');
const reply=(r,label,anchor=100)=>r.resolve({ok:true,json:async()=>({rows:[{raw_text:label}],total:60,anchor_id:anchor})});
(async()=>{
 await new Promise(r=>setImmediate(r));
 const first=run("liveScope='1';refreshLiveArchive()"),second=run("liveScope='2';liveArchiveAnchor=null;refreshLiveArchive()");
 reply(requests[1],'second');await second;reply(requests[0],'first');await first;
 assert.equal(run('liveArchive.rows[0].raw_text'),'second','Late prior session cannot replace chosen session');
 const next=run('livePage=2;refreshLiveArchive()');
 assert.match(requests[2].url,/offset=25/);assert.match(requests[2].url,/anchor_id=100/);
 reply(requests[2],'page 2');await next;
 assert.equal(run('livePage'),2);
 const stale=run("liveScope='3';liveArchiveAnchor=null;refreshLiveArchive()");run("mode='demo'");
 reply(requests[3],'wrong workspace');await stale;
 assert.notEqual(run('liveArchive?.rows[0]?.raw_text'),'wrong workspace');
 run("mode='live';liveScope='all';livePage=1;liveArchiveAnchor=null");
 const error=run('refreshLiveArchive(true)');requests[4].resolve({ok:false,json:async()=>({error:'synthetic'})});await error;
 assert.equal(run('liveArchive'),null);assert.match(run('liveArchiveError'),/读取失败/);
 const retry=run('refreshLiveArchive(true)');reply(requests[5],'retry',110);await retry;
 assert.equal(run('liveArchive.rows[0].raw_text'),'retry');
 assert.equal(run('liveArchiveAnchor'),110);
 const select=value=>({target:{id:'live-scope',value,closest:()=>null}});
 listeners.input(select('current'));await listeners.change(select('current'));
 listeners.input(select('all'));const version=run('liveArchiveSequence');await listeners.change(select('all'));
 assert.equal(requests.length,7,'Native input/change pair starts only one archive request');
 assert.equal(run('liveArchiveSequence'),version,'Duplicate change must not invalidate its own pending request');
 reply(requests[6],'native select',120);await new Promise(r=>setImmediate(r));
 assert.equal(run('liveArchive.rows[0].raw_text'),'native select','Native selection resolves instead of staying in loading');
 run("S.collector.model_queue={completed:13};livePage=2;liveSearch='player';liveFilter='accepted'");
 const pageTwo=run('refreshLiveArchive()');reply(requests[7],'old model result',120);await pageTwo;
 run('S.collector.model_queue={completed:14}');
 const background=run('refreshLiveArchive(true,true)');
 assert.equal(run('liveArchive.rows[0].raw_text'),'old model result','Background refresh keeps existing rows');
 assert.match(requests[8].url,/offset=25/);assert.match(requests[8].url,/anchor_id=120/);
 assert.match(requests[8].url,/q=player/);assert.match(requests[8].url,/filter=accepted/);
 reply(requests[8],'completed model result',120);await background;
 assert.equal(run('liveArchive.rows[0].raw_text'),'completed model result');
 assert.equal(run('liveArchiveModelKey'),'{"completed":14}');assert.equal(run('livePage'),2);
 run('S.collector.model_queue={completed:15}');
 const failedUpdate=run('refreshLiveArchive(true,true)');requests[9].resolve({ok:false,json:async()=>({})});await failedUpdate;
 assert.equal(run('liveArchive.rows[0].raw_text'),'completed model result');
 assert.match(run('liveArchiveError'),/上次结果/);assert.equal(run('liveArchiveModelKey'),'{"completed":14}');
 const lateBackground=run('refreshLiveArchive(true,true)');
 const changedScope=run("liveScope='18';liveArchiveAnchor=null;refreshLiveArchive()");
 reply(requests[11],'new scope',130);await changedScope;
 reply(requests[10],'stale background',120);await lateBackground;
 assert.equal(run('liveArchive.rows[0].raw_text'),'new scope');
 console.log('PASS: live archive native input/change, session races, stable pagination, workspace isolation and explicit failure/retry. Local fixtures only.');
})().catch(e=>{console.error(e);process.exitCode=1;});
